### ISSUE TITLE
csv import

### ISSUE THREAD

**Issue by rcsmit** [rdzudzar/DistributionAnalyser#2]
When my file is this

`tijden
56
18
37
15
30
34`

![image](https://user-images.githubusercontent.com/1609141/127484389-74dd5c8a-5f91-41a3-88bb-41660c6e3abd.png)
(ignore the linenumbers ofcourse)
This is shown

![image](https://user-images.githubusercontent.com/1609141/127484258-9fab2240-00c3-4c89-90c5-fcadbf034daf.png)

So I guess my file is not right or there is something wrong in the code?

Kind regards

**Comment by rcsmit** [comment]
Just continuing here to avoid opening too many issues. My data is https://github.com/rcsmit/streamlit_scripts/blob/main/input/schoonmaaktijden.csv

How can the SSE be 0.0?
![image](https://user-images.githubusercontent.com/1609141/127484713-dc1e5e2d-e904-4497-8758-07de3bb86fc4.png)

And I think the lambda has to be around 32 and the K 2.0?
![image](https://user-images.githubusercontent.com/1609141/127484805-b56f2863-f1a9-4911-a709-e537569586a1.png)
([source](https://docs.google.com/spreadsheets/d/1Lqddg3Rsq0jhFgL5U-HwvDdo0473QBZtjbAp9ol8kcg/edit?usp=sharing))

**Comment by rdzudzar** [comment]
Hi Rene, 
thanks for submitting the issues. 
I'm glad that Distribution Analyser can be of use.

1) Ah, this is some code bug which apparently happens when a .csv file has only one column - I will look to see to correct this. This affects column name, however data can be still loaded and used (probably into 0: "").

2) Feel free in the future to open separate issue - as it's not related to the first one. 
- I would have a question about how did you derive parameter values 32 and 2? 
- Also, in Scipy, for k=2 `Weibull_min` reduces to `rayleigh` distribution - so that might be of interest exploring. 
- The SSE on the plot is rounded - which is why appears as 0, if you look into the Table for it, it will be some small value above 0. 
- Another thing to look at is at `Scipy` Issues - as Distribution Analyser just uses their functions. I noticed that there is an issue with `Weibull_min` which may help with your question, see here: https://github.com/scipy/scipy/issues/11806

Cheers,
Robert

**Comment by rcsmit** [comment]
Thanks for the reply!

I used this piece of code https://gist.github.com/aw3s0me/cb2891d188e88df38f00 

Maybe the difference is in the loc=0 

I'll look into the other info!

**Comment by rdzudzar** [comment]
Was fixing some bugs and noticed that this was still open issue, sorry about that. 

There was typo in function for file import, now that is fixed - in case it's needed in the future. 

![Screenshot 2024-04-03 at 20-53-42 DistributionAnalyser · Streamlit](https://github.com/rdzudzar/DistributionAnalyser/assets/33647339/9d80cce1-e8d3-46f5-ba09-2db20db45518)
